### ISSUE TITLE
How to trade

### ISSUE THREAD

**Issue by altcnews** [rdenadai/bitfinexbot#1]
Hi,
I've been configuring the requirements and nicely open the rethinkdb in ui, but how to trade after that? Seems that nothing is happening. Do i have to run another script?

Please advice.
Thank You.

**Comment by rdenadai** [comment]
If you have money in your account and place the bot to access it using the API Key... it should by and sell for your...

Keep in mind you should open the config.json file and set the values for the coins you want to buy / sell and the amount of money... 

Change the "amount" value in the config.json because bitfinex forces you to buy / sell and minimum amout of coins!

PLEASE... TEST BEFORE USE FOR REAL... MAKE SURE YOU PUT JUST A LITTLE MONEY FOR THE BOT TO WORK ON!

GO TO YOUR ACCOUNT AND PLACE A FEW DOLLARS TO BUY / SELL AND LEAVE THE REST IN OTHER PLACE....
GO TO YOUR ACCOUNT AND PLACE A FEW DOLLATS
